listener:
  # serverPort: 80 # k8s probes, optional
  slotName: telegram_notifications_slot #‚ wal_listener
  refreshConnection: 30s
  heartbeatInterval: 10s
  filter:
    tables:
      category:
        - insert
        - update
        - delete
  topicsMap:
    public_category: "db-changes"
logger:
  level: info
  fmt: text # 

database:
  host: host.docker.internal
  port: 5432
  name: general
  user: partners
  password: 123
  debug: false
  enableTLS: false # Enable TLS connection to PostgreSQL
  # sslMode: "require" # TLS mode when enableTLS is true: require, verify-ca, verify-full

publisher:
  type: kafka
  messageKeyFrom: id # Kafka only
  address: kafka:9092
# enable_tls: true # Kafka only
  # client_cert: "cert.pem" # Kafka only
  # client_key: "key.pub" # Kafka only
  # ca_cert: "ca.pem" # Kafka only
  topic: "wal_listener"
  topicPrefix: ""
monitoring:
  sentryDSN: ""
  promAddr: ":2112"
